set(SRC_FILES
    src/audio/audio_capture_worker.cpp
    src/audio/audio_playback_worker.cpp
    src/app/app_runtime.cpp
    src/app/app_style.cpp
    src/codec/h264_decoder.cpp
    src/codec/h264_decoder_cleanup.cpp
    src/codec/h264_decoder_convert.cpp
    src/codec/h264_decoder_decode.cpp
    src/codec/h264_encoder.cpp
    src/codec/h264_encoder_codec.cpp
    src/codec/h264_encoder_frames.cpp
    src/codec/h264_encoder_hw.cpp
    src/codec/hardware_context_manager.cpp
    src/common/logger_manager.cpp
    src/desktop/desktop_capture_manager.cpp
    src/desktop/desktop_capture_worker_cpu.cpp
    src/desktop/desktop_capture_worker.cpp
    src/desktop/desktop_capture_worker_gpu.cpp
    src/desktop/desktop_capture_worker_gpu_scaler.cpp
    src/desktop/desktop_capture_worker_gpu_state.cpp
    src/desktop/desktop_capture_worker_subscribers.cpp
    src/desktop/desktop_capture_worker_timer.cpp
    src/desktop/desktop_grab.cpp
    src/desktop/desktop_grab_factory.cpp
    src/desktop/desktop_grab_qt.cpp
    src/main.cpp
    src/terminal/native_terminal_widget_callbacks.cpp
    src/terminal/native_terminal_widget_input.cpp
    src/terminal/native_terminal_widget_mouse.cpp
    src/terminal/terminal_file_panel.cpp
    src/terminal/native_terminal_widget.cpp
    src/terminal/native_terminal_widget_render.cpp
    src/terminal/terminal_session.cpp
    src/terminal/terminal_session_unix_pty.cpp
    src/terminal/terminal_session_windows_io.cpp
    src/terminal/terminal_session_windows_pty.cpp
    src/ui/app_title_bar.cpp
    src/ui/control_window_commands.cpp
    src/ui/control_window.cpp
    src/ui/control_window_input.cpp
    src/ui/control_window_actions.cpp
    src/ui/control_window_android.cpp
    src/ui/control_window_layout.cpp
    src/ui/control_window_state.cpp
    src/ui/control_window_toolbar.cpp
    src/ui/control_window_video.cpp
    src/ui/file_transfer_window_browser.cpp
    src/ui/file_transfer_window.cpp
    src/ui/file_transfer_window_tasks.cpp
    src/ui/main_window_client.cpp
    src/ui/main_window.cpp
    src/ui/main_window_events.cpp
    src/ui/main_window_ui.cpp
    src/ui/password_line_edit_util.cpp
    src/ui/settings_window.cpp
    src/ui/terminal_window.cpp
    src/util/config_util.cpp
    src/util/convert_util.cpp
    src/util/ffmpeg_util.cpp
    src/util/file_packet_util.cpp
    src/util/file_packet_util_file.cpp
    src/util/file_packet_util_receive.cpp
    src/util/file_packet_util_send.cpp
    src/util/i18n_util.cpp
    src/util/input_util.cpp
    src/util/json_util.cpp
    src/webrtc/webrtc_cli_channels.cpp
    src/webrtc/webrtc_cli_audio.cpp
    src/webrtc/webrtc_cli_control.cpp
    src/webrtc/opus_duplex_media_handler.cpp
    src/webrtc/sdp_quality_patcher.cpp
    src/webrtc/webrtc_cli_cleanup.cpp
    src/webrtc/webrtc_cli_files.cpp
    src/webrtc/webrtc_cli_input_dispatch.cpp
    src/webrtc/webrtc_cli_lifecycle.cpp
    src/webrtc/webrtc_cli_signaling.cpp
    src/webrtc/webrtc_cli_file_transfer.cpp
    src/webrtc/webrtc_cli_input_channels.cpp
    src/webrtc/webrtc_cli_peer.cpp
    src/webrtc/webrtc_cli_senders.cpp
    src/webrtc/webrtc_cli_terminal.cpp
    src/webrtc/webrtc_cli_video_send.cpp
    src/webrtc/webrtc_ctl_cleanup.cpp
    src/webrtc/webrtc_ctl_audio.cpp
    src/webrtc/webrtc_ctl_lifecycle.cpp
    src/webrtc/webrtc_ctl_peer.cpp
    src/webrtc/webrtc_ctl_reconnect.cpp
    src/webrtc/webrtc_ctl_signaling.cpp
    src/webrtc/webrtc_ctl_channels.cpp
    src/webrtc/webrtc_ctl_file_transfer.cpp
    src/webrtc/webrtc_ctl_media.cpp
    src/webrtc/webrtc_ctl_network.cpp
    src/webrtc/webrtc_ctl_video.cpp
    src/websocket/ws_cli.cpp
)

set(HDR_FILES
    src/audio/audio_capture_worker.h
    src/audio/audio_echo_suppression.h
    src/audio/audio_playback_worker.h
    src/app/app_runtime.h
    src/app/app_style.h
    src/codec/h264_decoder.h
    src/codec/h264_encoder.h
    src/codec/hardware_context_manager.h
    src/codec/codec_info.h
    src/common/constant.h
    src/common/logger_manager.h
    src/common/object_lifecycle.h
    src/common/platform_headers.h
    src/common/protocol_constants.h
    src/common/qt_rtc_metatypes.h
    src/desktop/desktop_capture_manager.h
    src/desktop/desktop_capture_worker.h
    src/desktop/desktop_capture_plugin.h
    src/desktop/desktop_grab.h
    src/desktop/desktop_grab_factory.h
    src/desktop/desktop_grab_qt.h
    src/terminal/terminal_file_panel.h
    src/terminal/native_terminal_widget_colors.h
    src/terminal/native_terminal_widget.h
    src/terminal/terminal_session.h
    src/ui/app_title_bar.h
    src/ui/adaptive_ui.h
    src/ui/control_window.h
    src/ui/control_window_view_helpers.h
    src/ui/file_transfer_window.h
    src/ui/main_window.h
    src/ui/password_line_edit_util.h
    src/ui/settings_window.h
    src/ui/terminal_window.h
    src/util/config_util.h
    src/util/convert_util.h
    src/util/ffmpeg_util.h
    src/util/file_packet_util.h
    src/util/i18n_util.h
    src/util/input_util.h
    src/util/json_util.h
    src/util/key_util.h
    src/webrtc/webrtc_cli.h
    src/webrtc/opus_duplex_media_handler.h
    src/webrtc/sdp_quality_patcher.h
    src/webrtc/webrtc_ctl.h
    src/websocket/ws_cli.h
)

set(UI_FILES
    src/ui/control_window.ui
    src/ui/file_transfer_window.ui
    src/ui/main_window.ui
    src/ui/settings_window.ui
    src/ui/terminal_window.ui
)

set(RESOURCE_FILES
    resource/qt/resources.qrc
)

set(TS_FILES
    resource/locale/airan-desk_zh_CN.ts
    resource/locale/airan-desk_en_US.ts
)
